{"numFailedTestSuites":1,"numFailedTests":0,"numPassedTestSuites":0,"numPassedTests":0,"numPendingTestSuites":0,"numPendingTests":0,"numRuntimeErrorTestSuites":1,"numTodoTests":0,"numTotalTestSuites":1,"numTotalTests":0,"openHandles":[],"snapshot":{"added":0,"didUpdate":false,"failure":false,"filesAdded":0,"filesRemoved":0,"filesRemovedList":[],"filesUnmatched":0,"filesUpdated":0,"matched":0,"total":0,"unchecked":0,"uncheckedKeysByFile":[],"unmatched":0,"updated":0},"startTime":1743812785620,"success":false,"testResults":[{"assertionResults":[],"coverage":{},"endTime":1743812786878,"message":"  ● Test suite failed to run\n\n    \u001b[96msrc/application/services/daily-fortune.service.ts\u001b[0m:\u001b[93m359\u001b[0m:\u001b[93m72\u001b[0m - \u001b[91merror\u001b[0m\u001b[90m TS2339: \u001b[0mProperty 'getContext' does not exist on type 'Result<SajuData, Error>'.\n      Property 'getContext' does not exist on type 'Success<SajuData>'.\n\n    \u001b[7m359\u001b[0m           console.error(`${logPrefix} エラーコンテキスト:`, compatibilityResult.getContext());\n    \u001b[7m   \u001b[0m \u001b[91m                                                                       ~~~~~~~~~~\u001b[0m\n","name":"/Users/tatsuya/Desktop/システム開発/AppGenius2/patrolmanagement/backend/src/tests/saju/daily-fortune-data-flow.test.ts","startTime":1743812786878,"status":"failed","summary":""}],"wasInterrupted":false}
